version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=emailn_dev
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=emailn_dev    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: start-dev
  